DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
    id BIGSERIAL CONSTRAINT users_pk PRIMARY KEY,
    name VARCHAR(250),
    username VARCHAR(250) NOT NULL UNIQUE,
    email VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(250) NOT NULL,
    role_id BIGSERIAL NOT NULL CONSTRAINT users_roles_id_fk REFERENCES roles ON UPDATE CASCADE ON DELETE CASCADE
);