name: Money Transfer Application

on:
  release:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Unit Tests And Integration Tests
        run: mvn -B package --file pom.xml

      - name: Build The Money Transfer Application and Publish to GitHub
        run: |
          mvn clean install
          mvn -B package --file pom.xml
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: arlannomad/money-transfer-app
          tags: latest
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

