name: Build and Deploy Money Transfer Service

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Money Transfer Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Money Transfer Service
        run: |
          mvn clean
          mvn -B package --file pom.xml
